# Generated by Django 3.2.5 on 2021-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0002_food_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fooddescription',
            field=models.CharField(max_length=2000),
        ),
    ]
